version: '3.8'
services:
  devcontainer:
    build: 
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../:/workspace
    ports:
      - 19000:19000
      - 19001:19001
      - 3000:3000

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  gcloud:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    restart: unless-stopped

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
