version: '3.8'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  editor:
    build:
      dockerfile: editor.Dockerfile
    command: sleep infinity


volumes:
  db-data: {}
