version: '3.8'
services:
  editor:
      build:
        dockerfile: editor.Dockerfile
      command: sleep infinity
  backend:
    build: sign-management-api
    command: cargo watch -x run
    working_dir: /code
    volumes:
      - ./sign-management-api:/code

  admin:
    image: node:buster
    command: npm install; npm run start
    working_dir: /code
    volumes:
      - ./admin-panel:/code
  
  delivery:
    image: node:buster
    command: npm install; npm run start
    working_dir: /code
    volumes:
      - ./volunteer-app:/code

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080


volumes:
  db-data: {}
