spin_version = "1"
authors = ["root"]
description = ""
name = "sign-management-api"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "sign-management-api"
source = "target/wasm32-wasi/release/sign_management_api.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"
