spin_version = "1"
authors = ["lee-orr <lee-orr@users.noreply.github.com>"]
description = ""
name = "api"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "api"
source = "target/wasm32-wasi/release/api.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
